let productsMock = [
    {
        "_idProd": 1,
        "title": "Camiseta Tirantes Gimnasio Mujer",
        "price": 39.56,
        "description": "Con su diseño de tirantes anchos, esta camiseta proporciona una gran libertad de movimiento en los hombros y los brazos, lo que resulta esencial para los ejercicios de levantamiento de pesas o de entrenamiento de brazos. Además, su tejido transpirable y elástico permite una gran ventilación y evita la acumulación de sudor en la piel.",
        "category": "mujer",
        "image": "http://localhost:5173/server/storage/camiseta_tirantes_gym_mujer.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 104,
        "brand": "Naik",
        "exclusive": true
    },
    {
        "_idProd": 2,
        "title": "Estuche Para Accesorios de Mujer",
        "price": 33.89,
        "description": "El Estuche Para Accesorios de Mujer es la solución ideal para mantener todos los accesorios organizados y en perfecto estado. Este estuche está diseñado con materiales de alta calidad y un acabado elegante que lo hace perfecto para llevar en cualquier ocasión",
        "category": "mujer",
        "image": "http://localhost:5173/server/storage/estuche_accesorios_.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 128,
        "brand": "Carlin Klair",
        "exclusive": true
    },
    {
        "_idProd": 3,
        "title": "Sudadera Celeste Niña",
        "price": 34.05,
        "description": "La Sudadera Niña con Estampado es la prenda perfecta para las niñas que buscan comodidad y estilo en su día a día. Esta sudadera está diseñada con materiales suaves y resistentes que garantizan una sensación de bienestar y durabilidad. Con su estampado divertido y colorido en la parte delantera, esta sudadera es una prenda juvenil y alegre que sin duda aportará un toque de diversión a cualquier conjunto. ",
        "category": "ninio",
        "image": "http://localhost:5173/server/storage/sudadera_celeste_niño.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 52,
        "brand": "Bucci",
        "exclusive": false
    },
    {
        "_idProd": 4,
        "title": "Sudadera Niño Con Estampado",
        "price": 23.72,
        "description": "La Sudadera Niño con Estampado es la prenda perfecta para los niños que buscan comodidad y estilo en su día a día. Esta sudadera está diseñada con materiales suaves y resistentes que garantizan una sensación de bienestar y durabilidad. Con su estampado divertido y colorido en la parte delantera, esta sudadera es una prenda juvenil y alegre que sin duda aportará un toque de diversión a cualquier conjunto. ",
        "category": "ninio",
        "image": "http://localhost:5173/server/storage/sudadera_blanca_niño.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 61,
        "brand": "Adimas",
        "exclusive": false
    },
    {
        "_idProd": 5,
        "title": "Camiseta Blanca Simple Niño",
        "price": 29.08,
        "description": "La Camiseta Blanca Simple para niño es la prenda esencial para cualquier armario infantil. Diseñada con materiales de alta calidad y con un corte clásico, esta camiseta es perfecta para el uso diario de los niños. Además, su suave tejido de algodón proporciona una sensación de comodidad y frescura durante todo el día.",
        "category": "ninio",
        "image": "http://localhost:5173/server/storage/camiseta_blanca_simple_niño.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 102,
        "brand": "Bucci",
        "exclusive": false
    },
    {
        "_idProd": 6,
        "title": "Camiseta Azul Simple Niño",
        "price": 40.43,
        "description": "La Camiseta Azul Simple para niño es la prenda esencial para cualquier armario infantil. Diseñada con materiales de alta calidad y con un corte clásico, esta camiseta es perfecta para el uso diario de los niños. Con su tono azul claro, esta camiseta es fácilmente combinable con cualquier pantalón o short, lo que la convierte en una prenda versátil y práctica para cualquier ocasión. Además, su suave tejido de algodón proporciona una sensación de comodidad y frescura durante todo el día.",
        "category": "ninio",
        "image": "http://localhost:5173/server/storage/camiseta_azul_simple_niño.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 41,
        "brand": "Carlin Klair",
        "exclusive": false
    },
    {
        "_idProd": 7,
        "title": "Camiseta Corta Rosa Mujer ",
        "price": 25.39,
        "description": "La Camiseta Corta Blanca para Mujer es la prenda perfecta para lucir fresca y moderna en cualquier ocasión. Esta camiseta está diseñada con materiales de alta calidad que garantizan su durabilidad y suavidad al tacto. Con su corte corto y ajustado al cuerpo, esta camiseta es ideal para combinar con pantalones o faldas de talle alto, lo que le da un toque de estilo y elegancia a cualquier look casual.",
        "category": "mujer",
        "image": "http://localhost:5173/server/storage/camiseta_corta_rosa_mujer.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 62,
        "brand": "Naik",
        "exclusive": false
    },
    {
        "_idProd": 8,
        "title": "Camiseta Deporte Blanca Mujer",
        "price": 42.54,
        "description": "La Camiseta de Deporte Blanca para Mujer es la prenda esencial para cualquier entrenamiento. Con su corte ajustado y sus mangas cortas, esta camiseta es ideal para ejercicios de alta intensidad que requieren una gran movilidad en los brazos y hombros. Además, su tono blanco puro aporta un toque de estilo y elegancia a cualquier outfit deportivo.",
        "category": "mujer",
        "image": "http://localhost:5173/server/storage/camiseta_deporte_blanca_mujer.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 110,
        "brand": "Adimas",
        "exclusive": false
    },
    {
        "_idProd": 9,
        "title": "Polo Negro Mujer",
        "price": 20.45,
        "description": "El Polo Negro para Mujer es la prenda esencial para un look casual y elegante al mismo tiempo. Esta prenda cuenta con un corte clásico que le aporta un toque sofisticado. Con su tono negro intenso, este polo es fácilmente combinable con cualquier pantalón o falda, lo que lo convierte en una prenda versátil y práctica para cualquier ocasión. Además, su tejido transpirable y resistente garantiza la durabilidad y la comodidad durante todo el día.",
        "category": "ninio",
        "image": "http://localhost:5173/server/storage/polo_negro_mujer.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 108,
        "brand": "Naik",
        "exclusive": false
    },
    {
        "_idProd": 10,
        "title": "Polo Verde Simple niño",
        "price": 32.79,
        "description": "El Polo Verde Simple para niño es la prenda perfecta para un look casual y fresco. Diseñado con materiales de alta calidad y con un corte clásico, este polo es la opción ideal para los niños que buscan comodidad y estilo al mismo tiempo. Con su tono verde suave, este polo es fácilmente combinable con cualquier pantalón o short, lo que lo convierte en una prenda versátil y práctica para cualquier ocasión. Además, su tejido de algodón suave proporciona una sensación de frescura y comodidad durante todo el día.",
        "category": "ninio",
        "image": "http://localhost:5173/server/storage/polo_verde_simple_niño.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 62,
        "brand": "LowCost",
        "exclusive": false
    },
    {
        "_idProd": 11,
        "title": "Polo Beige para Vestir Hombre",
        "price": 24.89,
        "description": "El Polo Beige para Vestir Hombre es la prenda clásica y elegante perfecta para cualquier ocasión formal o casual. Con su diseño atemporal y su tono beige suave, este polo es fácilmente combinable con cualquier pantalón o blazer. Diseñado con materiales de alta calidad, este polo cuenta con un corte clásico que le da un toque sofisticado y moderno al mismo tiempo.",
        "category": "hombre",
        "image": "http://localhost:5173/server/storage/polo_vestir_hombre.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 40,
        "brand": "Bucci",
        "exclusive": false
    },
    {
        "_idProd": 12,
        "title": "Camiseta Deportiva Hombre",
        "price": 38.21,
        "description": "La Camiseta Deportiva para Hombre es la prenda esencial para cualquier entrenamiento. Con su diseño moderno y materiales de alta calidad, esta camiseta está diseñada para proporcionar comodidad y soporte durante cualquier actividad física. Con su corte ajustado y sus mangas cortas, esta camiseta es ideal para ejercicios de alta intensidad que requieren una gran movilidad en los brazos y hombros. Además, su tejido transpirable y resistente permite una excelente circulación del aire y evita la acumulación de sudor.",
        "category": "hombre",
        "image": "http://localhost:5173/server/storage/camiseta_deportiva_hombre.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 120,
        "brand": "Naik",
        "exclusive": false
    },
    {
        "_idProd": 13,
        "title": "Camiseta Blanca Simple Hombre",
        "price": 21.68,
        "description": "La Camiseta Blanca Simple para Hombre es la prenda básica y versátil que todo hombre necesita en su armario. Diseñada con materiales de alta calidad y un corte clásico, esta camiseta es ideal para cualquier ocasión y combina perfectamente con cualquier outfit. Con su tono blanco puro, esta camiseta es fácilmente combinable con cualquier pantalón o short, lo que la convierte en una prenda práctica y esencial. ",
        "category": "hombre",
        "image": "http://localhost:5173/server/storage/camiseta_blanca_simple_hombre.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 106,
        "brand": "Naik",
        "exclusive": false
    },
    {
        "_idProd": 14,
        "title": "Camiseta 100% Algodón Niño",
        "price": 23.64,
        "description": "La Camiseta 100% Algodón para Niño es la prenda esencial para el día a día. Diseñada con materiales de alta calidad y un corte clásico, esta camiseta es cómoda, duradera y resistente al desgaste. Con su tejido de algodón suave y transpirable, esta camiseta es perfecta para cualquier actividad y brinda una sensación de frescura y comodidad durante todo el día. ",
        "category": "ninio",
        "image": "http://localhost:5173/server/storage/camiseta_algodon_niño.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 60,
        "brand": "Bucci",
        "exclusive": false
    },
    {
        "_idProd": 15,
        "title": "Camiseta Deporte Niño",
        "price": 48.63,
        "description": "La Camiseta Deporte para Niño es la prenda ideal para actividades físicas y deportivas. Diseñada con materiales de alta calidad y un corte cómodo, esta camiseta proporciona un soporte adecuado para los niños en sus actividades diarias. Con su diseño moderno y llamativo, esta camiseta es perfecta para lucir un look deportivo y fresco.",
        "category": "ninio",
        "image": "http://localhost:5173/server/storage/camiseta_deporte_niño.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 117,
        "brand": "Bucci",
        "exclusive": false
    },
    {
        "_idProd": 16,
        "title": "Camiseta Negra de Vestir Hombre",
        "price": 29.09,
        "description": "La Camiseta Negra de Vestir para Hombre es la prenda elegante y sofisticada perfecta para cualquier ocasión formal o semi-formal. Diseñada con materiales de alta calidad y un corte clásico, esta camiseta es cómoda y resistente. Con su tono negro profundo y su diseño minimalista, esta camiseta es fácilmente combinable con cualquier pantalón o blazer, lo que la convierte en una prenda versátil y práctica.",
        "category": "hombre",
        "image": "http://localhost:5173/server/storage/camiseta_negra_vestir_hombre.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 47,
        "brand": "Carlin Klair",
        "exclusive": false
    },
    {
        "_idProd": 17,
        "title": "Camiseta Gimnasio Hombre",
        "price": 40.01,
        "description": "La Camiseta de Gimnasio para Hombre es la prenda ideal para entrenar con comodidad y estilo. Diseñada con materiales de alta calidad y un corte deportivo, esta camiseta proporciona una gran libertad de movimiento y soporte adecuado para el entrenamiento. Con su diseño moderno y atractivo, esta camiseta es perfecta para lucir un look deportivo y fresco durante tus entrenamientos en el gimnasio. ",
        "category": "hombre",
        "image": "http://localhost:5173/server/storage/camiseta_gimnasio_hombre.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 106,
        "brand": "Carlin Klair",
        "exclusive": false
    },
    {
        "_idProd": 18,
        "title": "Camiseta de Vestir Hombre",
        "price": 46.63,
        "description": "La Camiseta de Vestir para Hombre es la prenda elegante y versátil perfecta para cualquier ocasión formal o semi-formal. Diseñada con materiales de alta calidad y un corte clásico, esta camiseta es cómoda, duradera y resistente. Con su diseño minimalista y suave al tacto, esta camiseta es fácilmente combinable con cualquier pantalón",
        "category": "hombre",
        "image": "http://localhost:5173/server/storage/camiseta_vestir_hombre.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 62,
        "brand": "Naik",
        "exclusive": false
    },
    {
        "_idProd": 19,
        "title": "Camiseta Azul Mangas Largas Simple Hombre",
        "price": 36.17,
        "description": "La Camiseta Azul de Mangas Largas para Hombre es una prenda básica y cómoda para el día a día. Diseñada con materiales de alta calidad y un corte clásico, esta camiseta es resistente y duradera. Con su diseño sencillo y suave al tacto, esta camiseta es fácilmente combinable con cualquier pantalón o chaqueta, lo que la convierte en una prenda versátil y práctica para cualquier ocasión casual.",
        "category": "hombre",
        "image": "http://localhost:5173/server/storage/camiseta_azul_mangas_largas_hombre.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 75,
        "brand": "LowCost",
        "exclusive": false
    },
    {
        "_idProd": 20,
        "title": "Sudadera Gris Hombre",
        "price": 44.19,
        "description": "La Sudadera Gris para Hombre es una prenda cómoda y práctica para los días más frescos. Con su tejido suave y transpirable, esta sudadera proporciona una gran comodidad durante todo el día. Su diseño moderno y deportivo la hace perfecta para lucir un look casual y fresco, mientras que su tono gris neutro la hace fácilmente combinable con cualquier pantalón o zapatilla. Además, su capucha con cordón y bolsillo frontal ofrecen protección adicional contra el frío y un espacio cómodo para guardar tus pertenencias.",
        "category": "hombre",
        "image": "http://localhost:5173/server/storage/sudadera_gris_hombre.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 49,
        "brand": "LowCost",
        "exclusive": false
    },
    {
        "_idProd": 21,
        "title": "Camiseta Yoga Mujer",
        "price": 29.95,
        "description": "La Camiseta de Yoga para Mujer es una prenda especialmente diseñada para brindar la máxima comodidad durante tus prácticas de yoga o meditación. Con su tejido suave y transpirable, esta camiseta permite una gran libertad de movimiento y flexibilidad, lo que te permite realizar tus posturas sin restricciones. Además, su diseño elegante y femenino la hace perfecta para lucir un look relajado y a la moda.",
        "category": "mujer",
        "image": "http://localhost:5173/server/storage/camiseta_yoga_mujer.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 42,
        "brand": "Carlin Klair",
        "exclusive": false
    },
    {
        "_idProd": 22,
        "title": "Camiseta Blanca Vestir Mujer",
        "price": 24.18,
        "description": "La Camiseta Blanca de Vestir para Mujer es una prenda clásica y atemporal que nunca pasa de moda. Con su corte sencillo y elegante, esta camiseta es ideal para lucir en ocasiones más formales. Además, su tono blanco puro y limpio aporta un toque de sofisticación y estilo a tu outfit, convirtiéndola en una prenda versátil y fácilmente combinable con cualquier tipo de pantalón o falda.",
        "category": "mujer",
        "image": "http://localhost:5173/server/storage/camiseta_vestir_mujer.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 82,
        "brand": "LowCost",
        "exclusive": false
    },
    {
        "_idProd": 23,
        "title": "Camiseta Morada Simple Mujer",
        "price": 28.43,
        "description": "La Camiseta Morada Simple para Mujer es una prenda básica y cómoda que no puede faltar en tu armario. Con su corte sencillo y suave al tacto, esta camiseta es perfecta para el día a día y para lucir un look casual y relajado. Además, su tono morado vibrante aporta un toque de color y alegría a tu outfit, convirtiéndola en una prenda atractiva y fácil de combinar con cualquier tipo de pantalón o chaqueta.",
        "category": "mujer",
        "image": "http://localhost:5173/server/storage/camiseta_morada_simple_mujer.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 89,
        "brand": "Adimas",
        "exclusive": false
    },
    {
        "_idProd": 24,
        "title": "Camiseta Patinaje Mujer",
        "price": 31.3,
        "description": "La Camiseta de Gimnasio para Mujer es una prenda especialmente diseñada para ofrecer la máxima comodidad y libertad de movimiento durante tus entrenamientos. Con su tejido transpirable y suave al tacto, esta camiseta permite una gran flexibilidad y transpiración, lo que te permite mantener una temperatura corporal adecuada y evitar la acumulación de sudor. Además, su diseño moderno y deportivo la hace perfecta para lucir un look fitness y a la moda.",
        "category": "mujer",
        "image": "http://localhost:5173/server/storage/camiseta_patinaje_mujer.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 94,
        "brand": "Adimas",
        "exclusive": false
    },
    {
        "_idProd": 25,
        "title": "Camiseta Gris Simple Mujer",
        "price": 34.83,
        "description": "La Camiseta Gris Simple para Mujer es una prenda básica y cómoda que no puede faltar en tu armario. Con su corte sencillo y suave al tacto, esta camiseta es ideal para el día a día y para lucir un look casual y relajado. Además, su tono gris neutro y versátil la hace fácilmente combinable con cualquier tipo de pantalón o chaqueta, convirtiéndola en una prenda práctica y funcional.",
        "category": "mujer",
        "image": "http://localhost:5173/server/storage/camiseta_gris_simple_mujer.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 63,
        "brand": "LowCost",
        "exclusive": false
    },
    {
        "_idProd": 26,
        "title": "Camiseta Patinaje Hombre",
        "price": 25.21,
        "description": "La Camiseta de Patinaje para Hombre es una prenda ideal para los amantes del skate y el streetwear. Con su diseño moderno y desenfadado, esta camiseta es perfecta para lucir un look urbano y fresco. Además, su tejido resistente y duradero la hace ideal para soportar los movimientos bruscos y las caídas propias de este deporte.",
        "category": "hombre",
        "image": "http://localhost:5173/server/storage/camiseta_patinaje_hombre.jpg",
        "rating": { "rate": 3.9, "count": 120 },
        "stock": 96,
        "brand": "Adimas",
        "exclusive": false
    },
    {
        "_idProd": 27,
        "title": "Camiseta Casual Slim Fit para hombre",
        "price": 29.18,
        "description": "Si buscas un look moderno y cómodo, esta camiseta es para ti. Diseñada con un corte slim fit y confeccionada en suave algodón, esta prenda es perfecta para el día a día. Disponible en varios colores, incluyendo blanco, negro y gris, podrás combinarla con cualquier prenda de tu armario.",
        "category": "hombre",
        "image": "http://localhost:5173/server/storage/camiseta_fit_hombre.jpg",
        "rating": { "rate": 4.1, "count": 259 },
        "stock": 84,
        "brand": "Adimas",
        "exclusive": false
    },
    {
        "_idProd": 28,
        "title": "Camiseta Rosa Simple Hombre",
        "price": 25.96,
        "description": "Añade un toque de color a tu armario con esta camiseta rosa para hombre. Confeccionada en algodón de alta calidad, esta camiseta es suave y cómoda al tacto. El diseño simple y elegante te permitirá lucir elegante en cualquier ocasión casual.",
        "category": "hombre",
        "image": "http://localhost:5173/server/storage/camiseta_rosa_simple_hombre.jpg",
        "rating": { "rate": 4.7, "count": 500 },
        "stock": 122,
        "brand": "LowCost",
        "exclusive": false
    },
    {
        "_idProd": 29,
        "title": "Camiseta Larga Vestir Hombre",
        "price": 43.77,
        "description": "¿Buscas una camiseta elegante para vestir? Esta camiseta de manga larga es perfecta para ti. Con un corte moderno y elegante, esta camiseta es ideal para combinar con pantalones de vestir y zapatos formales. Disponible en varios colores clásicos, podrás lucir elegante en cualquier evento.",
        "category": "hombre",
        "image": "http://localhost:5173/server/storage/camiseta_larga_vestir_hombre.jpg",
        "rating": { "rate": 2.1, "count": 430 },
        "stock": 41,
        "brand": "Bucci",
        "exclusive": false
    },
    {
        "_idProd": 30,
        "title": "Camiseta Anti-Manchas Roja",
        "price": 20.94,
        "description": " ¿Te preocupa manchar tu ropa? No te preocupes más con esta camiseta anti-manchas. Confeccionada en un tejido resistente a las manchas, esta camiseta te permitirá lucir siempre impecable. El diseño sencillo y moderno la convierte en una prenda perfecta para el día a día.",
        "category": "ninio",
        "image": "http://localhost:5173/server/storage/camiseta_roja_anti_manchas.jpg",
        "rating": { "rate": 2.6, "count": 235 },
        "stock": 68,
        "brand": "Carlin Klair",
        "exclusive": false
    },
    {
        "_idProd": 31,
        "title": "Conjunto Running mujer",
        "price": 33.71,
        "description": "Si eres una amante del running, este conjunto es para ti. Diseñado específicamente para la práctica deportiva, este conjunto incluye una camiseta transpirable y unos pantalones cómodos que te permitirán moverte con total libertad. Disponible en varios colores vibrantes, este conjunto te hará lucir bien mientras alcanzas tus objetivos deportivos.",
        "category": "mujer",
        "image": "http://localhost:5173/server/storage/conjunto_running_mujer.jpg",
        "rating": { "rate": 2.9, "count": 340 },
        "stock": 57,
        "brand": "Naik",
        "exclusive": false
    },
    {
        "_idProd": 32,
        "title": "Sudadera Negra con Capucha Niño",
        "price": 34.27,
        "description": "La Sudadera Negra con Capucha para Niño es una prenda cómoda y versátil, perfecta para cualquier actividad. Confeccionada en un suave tejido de algodón, cuenta con una capucha ajustable y un bolsillo frontal para mayor comodidad. Su diseño clásico y elegante en color negro la hace fácil de combinar con cualquier outfit.",
        "category": "ninio",
        "image": "http://localhost:5173/server/storage/sudadera_negra_capucha_niño.jpg",
        "rating": { "rate": 3.8, "count": 679 },
        "stock": 69,
        "brand": "LowCost",
        "exclusive": false
    },
    {
        "_idProd": 33,
        "title": "Mascarilla para Deporte Mujer",
        "price": 24.07,
        "description": "La Mascarilla para Deporte Mujer es un accesorio indispensable para cualquier rutina de ejercicio. Fabricada con materiales de alta calidad, es cómoda y transpirable, permitiendo una adecuada ventilación durante el ejercicio. Su diseño ergonómico se adapta perfectamente al rostro, proporcionando una protección eficaz contra las partículas en suspensión. Disponible en varios colores para combinar con cualquier outfit deportivo.",
        "category": "mujer",
        "image": "http://localhost:5173/server/storage/mascarilla_deportiva_mujer.jpg",
        "rating": { "rate": 4.7, "count": 130 },
        "stock": 52,
        "brand": "Carlin Klair",
        "exclusive": false
    },
    {
        "_idProd": 34,
        "title": "Leggins Yoga Mujer",
        "price": 27.03,
        "description": "Los Leggins Yoga para Mujer son la prenda perfecta para cualquier actividad física. Confeccionados en un tejido suave y elástico, se ajustan perfectamente al cuerpo para mayor comodidad y libertad de movimiento. Su diseño moderno y elegante, con detalles de malla y una cintura alta y ancha, los hace ideales para usar en cualquier ocasión.",
        "category": "mujer",
        "image": "http://localhost:5173/server/storage/leggins_yoga_mujer.jpg",
        "rating": { "rate": 4.5, "count": 146 },
        "stock": 119,
        "brand": "Adimas",
        "exclusive": false
    },
    {
        "_idProd": 35,
        "title": "Gorra Blanca Niño",
        "price": 40.87,
        "description": "La Gorra Blanca para Niño es un accesorio clásico y práctico, ideal para cualquier actividad al aire libre. Fabricada con materiales de alta calidad, cuenta con una visera curva y un cierre ajustable en la parte trasera para un ajuste perfecto. Su diseño moderno y juvenil en blanco la hace fácil de combinar con cualquier outfit casual.",
        "category": "ninio",
        "image": "http://localhost:5173/server/storage/gorra_blanca_niño.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 106,
        "brand": "Bucci",
        "exclusive": false
    },
    {
        "_idProd": 36,
        "title": "Gorra Verde Niño",
        "price": 25.15,
        "description": "La Gorra Blanca para Niño es un accesorio clásico y práctico, ideal para cualquier actividad al aire libre. Fabricada con materiales de alta calidad, cuenta con una visera curva y un cierre ajustable en la parte trasera para un ajuste perfecto. Su diseño moderno y juvenil en blanco la hace fácil de combinar con cualquier outfit casual.",
        "category": "ninio",
        "image": "http://localhost:5173/server/storage/gorra_verde_niño.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 58,
        "brand": "Bucci",
        "exclusive": false
    },
    {
        "_idProd": 37,
        "title": "Leggins Mujer Running",
        "price": 46.46,
        "description": "Los pantalones de running diseñados específicamente para corredores son imprescindibles para cualquier persona activa. Estos pantalones te ayudan a mantenerte fresco y cómodo durante tus carreras, a la vez que te proporcionan una ventilación y protección óptimas contra los elementos. Confeccionados con un tejido de primera calidad que absorbe la humedad, estos pantalones te mantendrán seco y cómodo durante todo el día.",
        "category": "mujer",
        "image": "http://localhost:5173/server/storage/leggins_mujer_running.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 57,
        "brand": "Bucci",
        "exclusive": false
    },
    {
        "_idProd": 38,
        "title": "Pantalones Fitness mujer",
        "price": 29.17,
        "description": "Nuestros pantalones de fitness están fabricados con materiales de calidad que te mantendrán cómodo durante tus entrenamientos, y ofrecemos una gran variedad de colores y estilos que se adaptan a cualquier estilo de vida. Tanto si entrenas en casa como si vas al gimnasio, con nuestra selección de pantalones te sentirás como nunca.",
        "category": "mujer",
        "image": "http://localhost:5173/server/storage/pantalones_fitness_mujer.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 74,
        "brand": "Naik",
        "exclusive": false
    },
    {
        "_idProd": 39,
        "title": "Camiseta Blanca Tirantes Gimnasio",
        "price": 27.84,
        "description": "La camiseta blanca de tirantes para gimnasio es perfecta para entrenar con comodidad y estilo. Fabricada con materiales transpirables y de alta calidad, esta camiseta te mantendrá fresco y seco durante tus entrenamientos. Su diseño de tirantes permite una mayor libertad de movimiento en los brazos, mientras que su corte ajustado te garantiza una silueta esbelta y atlética. Ideal para combinar con pantalones cortos o leggings deportivos, esta camiseta se convertirá en un básico imprescindible en tu armario fitness.",
        "category": "hombre",
        "image": "http://localhost:5173/server/storage/camiseta_tirantes_blanca_gym.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 115,
        "brand": "Lowcost",
        "exclusive": false
    },
    {
        "_idProd": 40,
        "title": "Camiseta Negra Tirantes Gimnasio",
        "price": 30.96,
        "description": "La camiseta negra de tirantes para gimnasio es una prenda versátil y cómoda para entrenar con intensidad. Confeccionada con materiales de alta calidad y transpirables, esta camiseta te mantendrá fresco y seco durante tus sesiones de entrenamiento. Su diseño de tirantes permite una mayor libertad de movimiento en los brazos, mientras que su corte ajustado te garantiza una silueta estilizada y atlética. Ideal para combinar con shorts o leggings deportivos, esta camiseta te hará lucir y sentirte bien en cada entrenamiento.",
        "category": "hombre",
        "image": "http://localhost:5173/server/storage/camiseta_tirantes_negra_gym.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 126,
        "brand": "Adimas",
        "exclusive": false
    },
    {
        "_idProd": 41,
        "title": "Sudadera Gris Con Capucha Niño",
        "price": 35.13,
        "description": "La sudadera negra con capucha para niño es una prenda de abrigo y estilo perfecta para los días más frescos. Confeccionada con materiales suaves y cómodos, esta sudadera te mantendrá caliente y a gusto en todo momento. Su capucha ajustable te permitirá protegerte del frío y la lluvia, mientras que su diseño moderno y atemporal te garantizará un look cool y desenfadado. Ideal para combinar con jeans, pantalones deportivos o shorts, esta sudadera se convertirá en una de las favoritas de tu pequeño.",
        "category": "ninio",
        "image": "http://localhost:5173/server/storage/sudadera_gris_capucha_niño.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 90,
        "brand": "Carlin Klair",
        "exclusive": false
    },
    {
        "_idProd": 42,
        "title": "Camiseta Tirantes Niño",
        "price": 36.57,
        "description": "La camiseta de tirantes para niño es una prenda fresca y cómoda para los días de calor. Confeccionada con materiales transpirables y de alta calidad, esta camiseta te mantendrá fresco y seco en todo momento. Su diseño de tirantes permite una mayor libertad de movimiento en los brazos, mientras que su corte regular te garantiza una silueta cómoda y casual. Ideal para combinar con jeans, shorts o pantalones deportivos, esta camiseta es perfecta para el día a día o para practicar deportes al aire libre.",
        "category": "ninio",
        "image": "http://localhost:5173/server/storage/camiseta_tirantes_niño.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 115,
        "brand": "Adimas",
        "exclusive": false
    },
    {
        "_idProd": 43,
        "title": "Camiseta Anti Manchas Niño",
        "price": 21.64,
        "description": "Esta camiseta está diseñada con tecnología avanzada que repele líquidos y evita que las manchas se adhieran a la tela. Con su suave y cómodo tejido de algodón, esta camiseta es perfecta para el uso diario de los niños, ya sea para jugar en el parque, para ir al colegio o para salir con amigos.",
        "category": "ninio",
        "image": "http://localhost:5173/server/storage/camiseta_anti_manchas_rosa.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 68,
        "brand": "Lowcost",
        "exclusive": false
    },
    {
        "_idProd": 44,
        "title": "Gorra Hombre",
        "price": 28.03,
        "description": "La Gorra de Hombre está confeccionada con tejidos transpirables que permiten la circulación del aire, lo que ayuda a mantener la cabeza fresca y seca durante los días más calurosos. Además, cuenta con una visera curva que protege los ojos de los rayos del sol y aporta un toque de estilo.",
        "category": "hombre",
        "image": "http://localhost:5173/server/storage/gorra_hombre.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 46,
        "brand": "Carlin Klair",
        "exclusive": false
    },
    {
        "_idProd": 45,
        "title": "Top Deportivo Mujer",
        "price": 24.51,
        "description": "El Top Deportivo Mujer es el aliado perfecto para las mujeres que buscan comodidad, soporte y estilo durante sus sesiones de entrenamiento. Este top está diseñado con materiales de alta calidad y tecnología avanzada para brindar el máximo rendimiento. Con su tejido elástico y transpirable, este top se adapta perfectamente al cuerpo de la mujer, permitiendo una gran libertad de movimiento mientras se realiza cualquier actividad física. Además, cuenta con un sistema de sujeción en la espalda que garantiza un soporte óptimo para el pecho, reduciendo así el riesgo de lesiones.",
        "category": "mujer",
        "image": "http://localhost:5173/server/storage/top_deportivo_mujer.jpg",
        "rating": { "rate": 3.6, "count": 145 },
        "stock": 112,
        "brand": "Naik",
        "exclusive": false
    }
]